### ISSUE TITLE
Cannot print passwords longer than 40 characters

### ISSUE THREAD

**Issue by 1f5** [Mr-Pi/WiFi_password_QR#1]
When entering a password longer than about 40 characters, the password is cut off. Length may vary depending on font and characters.
This does not apply to the SSID, since they aren't longer than 32 characters.
Proposed fix: reduce font size for passwords depending on their length.

Example (pw: ahthai2eiyop9ye7ohHeudooYeoVeecha4phohchoob3Jungoop2eichoh2ia7B):
![xahrahtaiz8oojie2shiesatoun9ne0e](https://user-images.githubusercontent.com/5995664/35226066-6ee0e534-ff8a-11e7-8f91-d4b42252ffe9.png)

**Comment by Mr-Pi** [comment]
This is fixed by https://github.com/Mr-Pi/WiFi_password_QR/commit/a6f0633b2b6e7afffa3421eb55d3780c6b8590e9
